Added html and css files for loading page
dscigdtuw/Indulge pull request #23
Opened 2020-10-29 08:48 UTC by aastha271100

**ISSUE NO** #2

2020-10-29 08:56 UTC, raksha009 commented on Aastha Bansal_loadingpage/loadingpage.html
> +</html>
Plz add a new line after line 28

2020-10-29 08:59 UTC, raksha009 commented
Plz also add a video of the code running on yr system.

2020-10-29 09:38 UTC, aastha271100 commented
I have made the changes. Please check.

2020-11-01 20:15 UTC, raksha009 requested changes
Hey! The video has to bee added in the pr and not inside the folder.

2020-11-02 05:55 UTC, raksha009 requested changes
Dear, plz have a look at this pr. https://github.com/dscigdtuw/Indulge/pull/24

2020-11-02 10:25 UTC, aastha271100 commented
https://drive.google.com/file/d/1ldd38gxDR_CW_2ad94iMmsAOnhUD1q1E/view?usp=sharing

2020-11-02 15:57 UTC, raksha009 approved these changes
Great Work!

2020-11-02 15:58 UTC, merged