Landing page
dscigdtuw/Indulge pull request #24
Opened 2020-10-29 10:41 UTC by khushi3108

**ISSUE NO** #2 

Added css and html for the reqd page

2020-11-01 20:16 UTC, raksha009 requested changes
Plz add a video of the code running on yr system and then we are good to go.

2020-11-02 05:23 UTC, khushi3108 commented
![Edited_20201028_082517_1](https://user-images.githubusercontent.com/60807052/97832761-a411da80-1cf9-11eb-91d8-e438d2b9508a.gif)

2020-11-02 05:36 UTC, raksha009 approved these changes

2020-11-02 05:36 UTC, khushi3108 commented
Requested Changes have been made!

2020-11-02 05:37 UTC, merged